package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestConvertSmallImage(t *testing.T) {
	converted := Convert(smallImageData)
	assert.Equal(t, converted, smallImageAscii)
}

func TestConvertBigImage(t *testing.T) {
	// Want to be sure that we resize the image to 80 columns
	converted := Convert(bigImageData)
	assert.Equal(t, converted, bigImageAscii)
}

const smallImageData = `
iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsTAAALEwEAmpwYAAACcmlU
WHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIg
eDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cu
dzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJk
ZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYv
MS4wLyIKICAgICAgICAgICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIj4K
ICAgICAgICAgPHRpZmY6WVJlc29sdXRpb24+NzI8L3RpZmY6WVJlc29sdXRpb24+CiAgICAgICAgIDx0
aWZmOkNvbXByZXNzaW9uPjU8L3RpZmY6Q29tcHJlc3Npb24+CiAgICAgICAgIDx0aWZmOlhSZXNvbHV0
aW9uPjcyPC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8eG1wOkNyZWF0b3JUb29sPkZseWluZyBN
ZWF0IEFjb3JuIDUuNi4zPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDx4bXA6TW9kaWZ5RGF0ZT4y
MDE3LTA1LTE5VDIwOjQ2OjE2PC94bXA6TW9kaWZ5RGF0ZT4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+
CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cr7Lp1sAABXXSURBVHgB7ZwJ1F1FkccrCVkhC0TIHhKW
IKCsAWRJSJyggAYQHBCOUQwgMAoCyshx0JMxOjDmgBNBYYjjgGIiOox4JGyChCXCQBBFI0gCkoSQhJB9
I4Bh/r/urvfue+++7dvgcFLn69d9+3ZXV/+7urq6771fp7dFtp1ajEDnFtfcXjEgsB3AVirCdgDfKwB2
6tRpQCv7EqqLz8C24NMojx0aLdge5dTZk8W3t8I+Cs/remUr29mm+gvFZ67iHyo8pzXysVbyrFm9U0ev
wurcEEn0RYXjFEbXlK71N9eJBQD2VLhMfX2q9SxLOXQYgAJuDzqhcLbCTgoQLtTfFTqloChS1y5mfXZU
uoaT1Um13nzLbN1mr1USo43ZGbZC18cKxOdKSrXyot0AFGATJJu6Z/0ULlfYP6UVBdCARjAF8MiznQVY
X03oLspdtdZs7aaQXfdnL+n0pi1mK1RnBy2Lb9BqJEAkMEjdFZYpHCcQ/6y4TahNARRoIyXVJQp7K5yY
I+GbygO0wurfS93qJ30EzWWrSmucMk49d/0svWW4/12lX8tkNR9PcAzY2Wzz62bdumoA1pdViIOJRr6q
cJNAvLKiRAsy2gRAATdTbZ+kIPHtfUkORp6pCXm6AFw3dWWQSi5aHgvw+6EPmF1whtnWrWbDB5sdeaAA
VE1nUiwZAQfAVwX6o783e2GJ2dQZxRIDBebyNcXrlEI3ARG6RCD+R0y2/LfVAAq8e9T88RkRfAIhqFuw
Tr26me2qTmG33pJWrVTntqaS551q9ol/MDtkP7Pddomctgk4wKtHgNtVvNdJ45ZKtwD1h7ebfedmTYOh
ZgteruDgIC4SgLtX3G0yo1UACrzL1N61Cm8o+MgGLWNqEgBiJ9m2xZjwMvq3i8xO+bDZSHV0B01swN2q
SZ6ncWVVSy6ZzthNwOus1lfLFn79erMf/Nzs/YJokSzfFiQsEoZBNexuhYsF5ILireZSLQZQ4H1CTX1f
QZMtTNHOdByV26W3OrFBiTK6+mJpnwBldT1xrNlQuc50+g2BBgjUDUzK6jVyGeonHt3RSLX/zRvMvjcr
1u4uu8jgZMg1cZ3yPi4QH8ncazjZIgAF3pVq4VupFfqN8gQABvc3e0V2CYM+en9NW03Js0+WYdT1PiNi
QTrrLgga2kla06zWpbZzI3gGEDeaPfkns2/PMHvkabMeAvH1UhBlbcPqvFrxGIE4P5dhjcymARR494nf
RxR8fSxo3iCBtQxRRE9q5AHsLY0zrgm0tXQahbyAfEi17c82DVIXDUx3udC/uMvsdDlS++9hNv/FinaA
VNAGF2e8QGzKT1QTjZPAY7Fw8KjbGQBQwRGDIngXfFI2516zg94ftWDHXhp1Afe6xpqy5aHx1psryaji
Am3dYjb+cLPPTozg7Tmkgg/gMZ3VA3tIfTykokSNjKYAFJ9piVdx2iq1u2zZkrRITJKgw4dGbaMDBDqD
ce9ook1W8l36ml0l7/SfTpe7szTKWyYLC6CG2NSTsCiW3a5+2XC3NDKTxeaDCqg8DQbNw9YtEngIeqMs
4wdHSdu0tQI01zbKvlOEHMwAbPC0L5v95NtRXlbnMuqma/XCxqmvzLKGqGEAxe2ixJHlP1BfTc8VazRF
RmvH/hOz8zXCuCMQ4JUTiwdAY+QJpMlrbwJEVnoWlonj1JFP6ZhmUfQTM20jsUvzlUx+zWRDi4hG5EFx
Ga/AwhEg2lXTYuU6rf9jzP5b6zHThJFG2DwCKFyWHYLuFkuwyHAgkAd4sVRzKV/lAxr6cd4MGtu8dVqd
v3F99BPda0gtUIWAYp2nBWVGyq8alXWnslyauj/SHXWz4CxbX+1fARCbx/RgMw94CBkojacLj2YulkO7
cEnsBGXQir2GmQ2T+QZILxsZVP9lhQ3dTG3gA2UHzvlwO+sfYRNpE69gqubTjlqhp90i+TX4r6kvqTTc
oRnq+74C8dl4mf9bF0BVk/sbKMhDCndloYzxWVqTjz9GQknzEBoNY0fg05I8tAtwumrkn3leW7ZLIzP/
/eV3zfYYqnLqmHfc71WLe2CtyghgnLx9v87yBUT22syYc0+LANIxXB5Migjtk8RBWc4noxbVBFAjsLcq
P5QY6DKCg2ti8vdOF4DsKjgBQcNWrIrTAxDRELQRR3onladTPbpHTgePivHTApS8MOT0ogGikxwcsLrj
gL+ta9oeuKs0qocOFp42u+E2Xb8vMlv+mtmFZ5gdfXDRxHRW+S2SeffBZld/yeyK6WajhutIfHEcRMnq
0pxcT6SaAKryWQpqJqy8XQFhqARd+LKOXo41G3uotI+xEqFhsx/WQjI1XvvvvFnxkMAXDfJf017VqTDl
QdHF9puZmLYZGAZr0hVm/5fZMxyhHc/sH8Q992pNxVn3ZCoqeeYJSbtTGzRDEuA5xJiiuoC3Wz+d7kTZ
NDShyEhpzRmaxhqSfKJgLZqQboZy/WU7Xl5phgZ95zI9zJD2BU1IHcdAQ6Nk14bvFtNoC6PNFOGUGSLN
VApUA7RUoiSiuGuXO8XhOvHBjED7j4yBdGHhyrTFbGJntPfuZg/frMNc2XTA6xnNAyWl44G0h6lO3o2K
EkIe9R2jAKMucMQNgL40Sdu0kWWrJ0OaiOMqVmToupkayjTyrnmAHudtJqZwgxT4qWzgo5hFxfM83rDZ
jAB5Xrwq/mIC2CEdpnPILzLXRANkchIx3Eg+Wlgc5JnlcVUAVVAwBZKVEXjSLg4JILZGLAwZzOL0SxlM
SxceAR98QtuohXLxb4n112yIcfhlZCCP41XNX283rMYqWXCPuJH4EBVYFhKlbD2bAcccQRuTNxGvAguM
VGaJSndSlAugEJdJtaNSmTDxONuDJksve8lYM6ouQLjBdYYb52/dNZ3myQmYqHX8n6+Jp8eULTmbczQ8
Dswa+3ENXPSK2RrZPo4ECjY1y6IOb24fup88CvUYd4ZHDBnK9CqTm5LVbmp9DYsH6IcyfqJy5onR76tw
foUmtg7COEOcOJPGHt41V/tl2U93F7xPBRejZDRi/Xq/W6TdOPRPPad97lQ9BxF/7DJU4Bsvq/5SDheK
/n3hzFgsPA2sWqP0RjUAfZKFbrE6/W2ZNGlMPGXB5yoXkJHfb8+Y/+qaIohMjyWvyu/SqOLsJl+rAHJw
oJHJES2VL/8qlUU4nPkhclnuecxs6o3RVFBpY7J/+QxKc+kLch4lS3fGR8xeWh5X5NJS+Vdpzaq4eVHK
CQD21JSFJp1k1l9gommFVTTeCsBwhMUK/NfF0roB8RgfjaO/azYJXMW+AmMboX594iJQag/ivdxfMSms
qqnA0tc0XQTidC1YUJ9emorr404j5tT5FU8UgJ3JEM0WyFfzeFVdugoNlP27RJWwf2JpnZmCm9JoHrBP
tH2JaTGSAL7S3fgNPecYF8HjoQ7ayxMydi8DFdg27TM8LkjnfzKeWudpdJF5McUA4Dj7au6LCCVeEYg8
SsAdWS95y2dIkUtOSiMMb0B0v9b7k0pzO5fyNPDIVFJKbZ05rmKEp1wQn2HkbblC4xKCURun2uxI7piT
+0QssOYEZ98Req44KWpTo/tgAMPX5HEnR/RoC7Z4Y7K92ecwAOAAZ/fJQYCcHxUPlFOWW5o/+ZQHYNK3
qLbuHO8trUHFN7PMV+htHEFa4iyQB0ZP/DR2oFwTAJtOD9o1bqVwZsvL5IlKGTQEX/Sr50Qn2KcsuyNs
a1ZNkGVnaST217Uqj2/Iy1R0IJVPrriG06fzQrmcnzwAS+AJ+1pVZFrQgVqd5R4jD+ijP5DTWspCMne2
c0a8akX4U4+ToK+pSweMMrvmFrO//C2/ir/pwE6lbEqWVgA1hCpG8SICCB7jPKM8zgOwUIatG/teVt/j
jy56/oUCOQnXFHdpcoqELMo1A57zoR6PJ1l8zj5FD2gk131zzeZqSvcRsAwyeLBYce53oOw2QNe0swk8
byMn1lqfT1UBRFAc5lVyaL7yObMRWhA2Swvzpm85a+oS2osAHieagCn49ESzT8k/rddkvfvIWya3z8Zj
tbgerkOFJ8r7VBVAhOQhOASQ2yTsu4m8o5ztMahs1n0mEjdFqgA/6q2X1kKJPwDKYof3Cw8iv5wc4fL8
kq1aMNCNDF8Fl/bP8BnBWIeVN8WA4aGeFIDFio0XwU4L8hMkJb3naa0Ptws/VTWwUC3DoVDrXZgIvfSu
etyEnIDPgsnpOMR1MBXxkt9cZcvNDHXEwKcJjD1d5PceSwl0QNNfIHZOfn5Zq6dVAUSlYQjd/3jR//MG
4p22/w2dSG17uu1bqeSItuGTjhisM8wr4n1ex6tHVQGkor/LgpuA/xXsTTsjiPvB9hGt91CvE211n67R
Ju4Q5PY1XuX/5gFYgIgtElP3t/PM/vCcmOeVzufb4lyOqDiM5TEpe3BOVfwEJ4+pa2k2zivXSB6mEz5+
zlgAokblvEVE+4hIOKx7yajiTD//Ujy1pYH2sIfwZRX8rzv10uEsPc/YM275eKp269Uy7sOKT9VcPmLq
IE+2s3+X45G9zpavl4ZXM/3LA3BttpGVq+PVHb81O2Gsnhn0jweQzTSS5VczLeE5WX72pRi8LOYD7Qio
JLC4BvSZs81e1ACzT3cz8zntUHbuq2sB2S5yumCK8wC8VvmfVpAItk3fYHTmwHL2o3ppWye+vBjeXlqo
9sLjUWJe/sGp5TkMIFTTqN/oIPXWu6hRpLM+Fl2QYk77pSqsmrYrL6i5MODerI/ir+fEvWb22YeXaauY
wYFYwNjL1iMe3EMH7BWP93lAzoraUVQBYGr4xykO3VmbDvivVS5P1/hEwTvanoL6wNVqg2kLISPH+25y
Ym77/1YDUBMjUACQ1ZivgTZoZeRFSpb6jgCwovsZzcokQzG/bgT0Cr6tyMgFUNP4p+K5QAEbGcbYj9Hv
nKPXYjTSPJfocBAzhtCTDpzkfEcoF8Akyc+yEm2Wf8Zb7v95e/yOzU+qs2XaK10xUEIPTWMmcP73TlIt
AOWNBZKY9rYfi2P/Jn/dbI5OxuhERedSpbaInHc3HeOXLwxc8zLT9bdFm9zIgtOQTBocb7eR8lUB1DT+
ixj8b2ISxplvLPrrJPjRP+i5xHfjDgFHtj20gL24vw7HqyHsUNhasSvhMeu92l6eemmUjh1S2Uc0jfQ9
v4wGxrdwStalqgCmmjooD1SYKLz6sGP36PDSMV4iapdFRQDyDg2PQ8+dopcUtZ3sIeA43F2y3OzK66Jg
g/oLXMngGtra7Sba5y9rNqKJ9QD8ucRkL8L2Liwmb+qX6czHghMv0nt6z+hJmQCFGmkwlmzsFy3cJA8A
+vwUTYf79Pzjd9oRXWD2Ry1xgMeDIzTF98thcaNCk0Rb2HU+n/2X6bHyKilLPaoJoKbxX8Xgl4kJcqoZ
beUEImDxEHvC57V//Z9oDxG+tdPZNSk0pLZ4GsiH2DyePO3Lerh1Yfxghof0ATxJRdnevZCsCKjXj7n1
f30QHvtj9Cd5+Ry3rR7VBJDKAvEcRbJ44US2MJX5zN6d2HP/Nb7CxkN3jqJaA6K/Fuf2Dxk43GSweKuB
mBeKljMvRAwk7934U8D7b4ovPzWzD4aH273ZDyW+Mcr+FvqezWzoMwcq6KkUCi3R4+u+jFgYedkkvrp8
dpHZr6T6PFQHQDrgQqloXaITLEgcmx12Viy+x+AITFjtlYV2kg7PaHRN+3gFvNPHF+oPzDD78BHxpUnu
IWMjRNsM/INPmn1U5gF3jSmdPA/1JPjDuZ89NAPg6WI0MzHDHoa3VhGUly/RDl4BuepifXWukv16xwUG
4eh0I0RZVlie8R7z2UZqFMvMvCq+9M5bD820yWCj7RybDZkQ+aHRq+M+nO4hPdrH/1p4IJYo/jYMIFWk
hWcqmpWq+8iES/7ZA69SsB+98B/1QuXkePSF1gQDr9jtW6pfESEtasXrG/Pmy2nXEsb7fgCSR2j4Gmke
36qMOyyeHzYDHmXhQXzDz/QvRa4xGzkovsoHasr2Pj4m8I7Mk6EpAGEgEGE0R4G1V1YvrNCK4jRgZcTg
Q3z+dcQBxSnn7kEtjXQAmFJoUyPE1Mcee91G6lCWgPY9/JTZ+HPiFwhLtQor2ynMNF18VQD+u2dm46YB
pLJAZDqjiepm+NxfOlMk3khdLBAnHK6peIjZyeOljTpH5P8h0FGOzDkSY5TzKHRAP1mgk0aEOpkOxvmV
MrLlq/EFNKYtB7B8OcVX7XxJ8NDv9ZmEzIe/6aX6Dt5GgadJnU8tAhBWAvE0Rbcntmii9CD2mf7wXg2v
hWTpXgk75tA4RdFGOgNV63i4ncoUkHPUyU+oVqsfmKcfQGO68j0LzjbPWqb9SABq1YbYHGzaGtP6de5k
nCAA7y7cKUu0GED4CMSxirT22sFciySmTJ06Bji4HEwR0u528EH25FP10s+o4g6G1Q4sGgGCRhol2iUA
HHaVQVuwKK7Sdz+iDw41oJx8L10hn08OexoP2L+hwKz6tcCbSEY1ahWAzlRA3qw0zgeNoo3IwvQmDsDw
9iguh/9LgG99Ie5f+QTro8cordFHS+gwteotOPDNIwcNEwEPdhe4VPNfMLvtHn3aJa1z4r1CPhwqI5+6
ZI8WgPPK7pdctgmAcBSIUxQRspQVJgAZ9q4a7TXpuP4gaeJ1X9PnYPtGP9B3M2GKi1MYgSxHpcEY4l7C
O1wDHlOUBQjQ4PGnBfrPRs+YXTotFAmzgm/3+ECSfxVVRll5+Xco3yu7X3HZZgDCWSAepehyhUEKH1KA
1JWiNpLBKxN8EdRLhpxv1KDPfCy+lHmc1nim23BxYOqx4ODUZgkbxr0CkilJHv/JiP+79cDj+scXcoV+
fGesyYMxgOVdat46C5oeb2F2CMipZST8L5lzBd5SpetSmwKYbU1gnqTrmxQGpnyERGlKlKq3RMZ5Th/5
paJ6Niyt5HuNsaOjU+7bRk5+sFkcYkBub0lz744HtHl/kKtIvOTeU3aYf0sAudYqiTxonHS2QHMF3NGF
qwYS7Qagty0gr1b6Cr9WjNAOZAATzWB/CwAcj6WPn0OV0ZrawzQE+IQU7iI7ekcGoFCo7IeDBrQUm4pj
7+CrGLpMyAKHFbxfYa3Au1BxU9TuACKNQDxWEUIfqPB9Bcg7QlrQRc2k4+xF+Qqe9IuvcLuS+FIzvIIR
hkD3xQ1t3LBJ2zC5T5lpn21H8BdovVLIMl3ALS/kNpnoEACzMgnMy3V9iYIgKCFsEHA4JOFmn55xJS3Y
LN3l8CDnBNpNRAnTxE9DUaBFSt2qMFPAzS/ktjDR4QAip0AcoGiYwmUKAMmCI0vVbqTjCfuzwnSFJQIu
WcTWt/eOAFgutgAdo7yRClqL7eMKGxWyWqPLuqSjB3tUQUtSwdYxZdcLsF8obhd6VwCY7ZnAHIhNUqwd
dSRdp+OJeO33yCddft/rdUT8rgOwIzrdlm00O03asu33BK/tALZyGLcD2EoA/x/lJUTlKjlwmgAAAABJ
RU5ErkJggg==`

const smallImageAscii = `................................................................................
................................................................................
...............................0QC$vvvvvvvvvvvvvvvvv$zQZ........................
..........................mJ$$$$$$$$$$$@@@@@@@@@@$$$$$$$$$$m....................
...................mJX$$$$$$$$$$$BB@B%@#MMMMMMM#&%BB@@$$$$$$$C..................
................X$$$$$$$$$$BBB@B$owz(|1---------](f00hB%$$$$$$$.................
..............0$$$$$$@$@@B$bkdQ/]___--------------___-xa%$$$$$$$$O..............
............X$$$$$$BB$Qux{]____--____________________-_?{Q$8$$$$$$$m............
...........$$$$$$B%$c?___--____________________________-_-na%B$$$$$$$...........
..........$$$$$@BWZ|-_-____------________________________-__|a%%$$$$$$..........
........Q$$$$$&$C-_-------_]{{{{]_-__________-----___-__-__-_-xhB@$$$$$m........
.......m$$$$$&$U___?]]]]?-+j$88$j+-_________-]]]]]-_{xjjx{_-_-_]b@8$$$$$........
.......$$$$@B8z-_-+v$%B$t_+f$&&$f+-_______-_?k$%$k]+j$88$j+-__-_]O@B$$$$$.......
......$$$$$B$/+-_-+u$WB$a)]0$%&$f+-_______-_?d$&$p?+j$&&$f+-____-+v$&$$$$$......
.....$$$$$8$X-_-_-+v$W$$$BMB$$&$f+-_______-_?d$8@&z_f$&&$f+-____-_-J$8$$$$......
.....$$$$&$C-_-__-_1%@%$$$@$$$&$t+-_______-_?p$%$BBad@@&$f+-_____-_?Z$8$$$......
....$$$$B@k[_-_____-}C$%BBBBB88u_-________-_?w$&@$$@@$$&$f+-_____-_-0$8$$$......
....$$$$W$u+-______---}}}}}}}}]_-__________-_-rp8BBBBBB8$t+-_____-_-0$&$$$......
....$$$8$Y?_-________----------______________-__?|xjjjjx/__________-0$&$$$Z.....
....$$$8$|+-____________________________________-__-_-___________-__X$8$$$$.....
....$$$&$|+-______________________________________________________-+{$@@$$$.....
....$$$8$O-_-______________________________________________________-+v$W$$$.....
....$$$$%$r+-_____________________-_/Xuuz[_-_______________________-+u$W$$$.....
....$$$$@BM1+-____________________-+U$%B$1+-___-Jhbkb[_-___________-+u$W$$$.....
.....$$$$%$b[_-___________________-+Y$W@$1+-___-Q$M@&}+-___________-+u$W$$$.....
.....0$$$$&$X-_-__________________-+Y$WB$1+-___-0$&$%}+-___________-+u$W$$$.....
......$$$$$@$X{--_________________-+Y$W@$1+-_-_)a$8$%}+-___________-+u$W$$$.....
.......$$$$$B$*)_--_______________-+Y$&@Bp1+_?Q$B$@$%}+-___________-+v$W$$$.....
.......m$$$$$$B@m(-_-_____________-+Y$&$@@Bwm8BB$$B$B}+-__________-_\@B@$$$.....
.........J$$$$$@@%w)__-___________-_n$%%BB8888BBB%$m{____________-_1*$B$$$$.....
..........0$$$$$$$B@br?-_--________-_}O*aaaaaaaa*m(_--_________--_f$B@$$$$O.....
............Z$$$$$$$BB$U/[?__-______-__---_-_---__--________--_]rJ$%$$$$$L......
..............0$$$$$$$@@BB$mr}___--_____--_-__-_-______--___[[th%@$$$$$$O.......
.................U$$$$$$$$@BB@khL}-___--------------___-}\Oh@BBB$$$$$$$Z........
...................ZYz$$$$$$$$B%@B*d0Q|(?----]((((((v0d*BBBB$$$$$$$$Xw..........
........................J$$$$$$$$$BBB$B%&#MM#$%BBBBB@BBB$$$$$$$$$YJ.............
............................L$$$$$$$$$$$@@@@@$$$$$$$$$$$$$$$$Cm.................
.................................OQY$v$$$vvvv$$v$vJ0QQQQ0.......................
................................................................................
................................................................................
`

const bigImageData = `
iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAA
CxMBAJqcGAAAAjBpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRv
YmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRm
PSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpE
ZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRv
YmUuY29tL3hhcC8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29t
L3RpZmYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+QWNvcm4gdmVyc2lvbiAzLjUuMTwv
eG1wOkNyZWF0b3JUb29sPgogICAgICAgICA8dGlmZjpDb21wcmVzc2lvbj41PC90aWZmOkNvbXByZXNz
aW9uPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAg
ICAgPHRpZmY6WFJlc29sdXRpb24+NzI8L3RpZmY6WFJlc29sdXRpb24+CiAgICAgIDwvcmRmOkRlc2Ny
aXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgoHbBTiAAAfj0lEQVR4Ae3dYZLkNo4G0OmN
OUHd/4x9Ba/t3Yhqu6FMKiVSIPDmV1spUcSDquILBSrnx8+fP//4j/8RIECAAAECrQT+p1W1iiVAgAAB
AgT+FhAAPAgECBAgQKChgADQsOlKJkCAAAECAoBngAABAgQINBQQABo2XckECBAgQEAA8AwQIECAAIGG
AgJAw6YrmQABAgQICACeAQIECBAg0FBAAGjYdCUTIECAAAEBwDNAgAABAgQaCggADZuuZAIECBAgIAB4
BggQIECAQEMBAaBh05VMgAABAgQEAM8AAQIECBBoKCAANGy6kgkQIECAgADgGSBAgAABAg0FBICGTVcy
AQIECBAQADwDBAgQIECgoYAA0LDpSiZAgAABAgKAZ4AAAQIECDQUEAAaNl3JBAgQIEBAAPAMECBAgACB
hgICQMOmK5kAAQIECAgAngECBAgQINBQQABo2HQlEyBAgAABAcAzQIAAAQIEGgoIAA2brmQCBAgQICAA
eAYIECBAgEBDAQGgYdOVTIAAAQIEBADPAAECBAgQaCjw34Y1K5kAAQIECKQV+Pr6WrI3bwCWMLsJAQIE
CBDIJSAA5OqH3RAgQIAAgSUCAsASZjchQIAAAQK5BASAXP2wGwIECBAgsETAEOASZjchQIAAgU4Cqwb5
rph6A3BFz7UECBAgQGBTAQFg08bZNgECBAgQuCIgAFzRcy0BAgQIENhUQADYtHG2TYAAAQIErggYAryi
51oCBAgQaC2ww7DfUYO8ATiScZwAAQIECBQWEAAKN1dpBAgQIEDgSEAAOJJxnAABAgQIFBYQAAo3V2kE
CBAgQOBIQAA4knGcAAECBAgUFvBXAIWbqzQCBAh0Fth5Qn9F37wBWKHsHgQIECBAIJmAAJCsIbZDgAAB
AgRWCAgAK5TdgwABAgQIJBMQAJI1xHYIECBAgMAKAUOAK5TdgwABAgSmCXQY9vv58+ftft4A3E5qQQIE
CBAgkF9AAMjfIzskQIAAAQK3CwgAt5NakAABAgQI5BcQAPL3yA4JECBAgMDtAoYAbye1IAECBAjMEjDw
d5+sNwD3WVqJAAECBAhsIyAAbNMqGyVAgAABAvcJCAD3WVqJAAECBAhsIyAAbNMqGyVAgAABAvcJGAK8
z9JKBAgQIHCjgIG/GzGDpbwBCFAcIkCAAAEC1QUEgOodVh8BAgQIEAgEBIAAxSECBAgQIFBdQACo3mH1
ESBAgACBQMAQYIDiEAECBAj0EZjxf7W7g543ADt0yR4JECBAgMDNAgLAzaCWI0CAAAECOwgIADt0yR4J
ECBAgMDNAgLAzaCWI0CAAAECOwgYAtyhS/ZIgACB4gKrvvWv68Bf9Ph4AxCpOEaAAAECBIoLCADFG6w8
AgQIECAQCQgAkYpjBAgQIECguIAAULzByiNAgAABApGAABCpOEaAAAECBIoLCADFG6w8AgQIECAQCQgA
kYpjBAgQIECguIAAULzByiNAgAABApGAABCpOEaAAAECBIoLCADFG6w8AgQIECAQCWzxVcBXvyLSVz9G
rXeMAAECzwhc/Z0+umu/+19LeQPw2senBAgQIECgpIAAULKtiiJAgAABAq8FBIDXPj4lQIAAAQIlBQSA
km1VFAECBAgQeC2QbghwxnDIlTUNkbx+gHxKgAABAnsKeAOwZ9/smgABAgQIXBIQAC7xuZgAAQIECOwp
IADs2Te7JkCAAAEClwQEgEt8LiZAgAABAnsKpBsCzMZ4ZYDwr1oMEWbrqP0QILBS4Orv0JG9dvg9e9Ux
MvIGYOTpcg4BAgQIECgmIAAUa6hyCBAgQIDAiIAAMKLkHAIECBAgUExAACjWUOUQIECAAIERAUOAI0oX
zrk6uBHdOhrmiM5zjAABAqsEZvyuW7X3bPeZYRmt6Q1Ats7bDwECBAgQWCAgACxAdgsCBAgQIJBNQADI
1hH7IUCAAAECCwQEgAXIbkGAAAECBLIJGALM1pGB/UTDHAYDB+CcQoDA9gLVftdFv89XNckbgFXS7kOA
AAECBBIJCACJmmErBAgQIEBglYAAsErafQgQIECAQCIBASBRM2yFAAECBAisEhAAVkm7DwECBAgQSCTQ
4q8AoqnRJycvZ/R/tJ7IYsZ+rEmAQF2B0d83VwX8vroq+Pp6bwBe+/iUAAECBAiUFBAASrZVUQQIECBA
4LWAAPDax6cECBAgQKCkgABQsq2KIkCAAAECrwVaDAFGBDOGS1YNxkT1jB67uscZbqN7dx4BAusFrv7O
WL9jdxwV8AZgVMp5BAgQIECgkIAAUKiZSiFAgAABAqMCAsColPMIECBAgEAhAQGgUDOVQoAAAQIERgXa
DgGOAp05b3RAbuehmtG9j1qc8XUuAQJzBUZ/vmfswu+MGaqv1/QG4LWPTwkQIECAQEkBAaBkWxVFgAAB
AgReCwgAr318SoAAAQIESgoIACXbqigCBAgQIPBawBDga58pn0bDLk8O38woMqonqnvGva1JgMA/BaKf
x3+esfa//C5Y6310N28AjmQcJ0CAAAEChQUEgMLNVRoBAgQIEDgSEACOZBwnQIAAAQKFBQSAws1VGgEC
BAgQOBIwBHgks/j41aGYbEM+Ed+MPV51i/bpGIFdBWb8jF218DP6LZitP94AfPfGvwgQIECAQBsBAaBN
qxVKgAABAgS+BQSAbwv/IkCAAAECbQQEgDatVigBAgQIEPgWMAT4bbH1v64M2mQbTDnTiGjvVyzO3Nu5
BAh8C/i5+7b461/R76Z/nvH8f3kD8HwP7IAAAQIECCwXEACWk7shAQIECBB4XkAAeL4HdkCAAAECBJYL
CADLyd2QAAECBAg8LyAAPN8DOyBAgAABAssF/BXAcvJ8NzwzvbvDZGu0xzM15uuQHRH4XSB6zn8/6/oR
PzvXDbOu4A1A1s7YFwECBAgQmCggAEzEtTQBAgQIEMgqIABk7Yx9ESBAgACBiQICwERcSxMgQIAAgawC
hgCzdibpvkYHglYNKI0yRfsZrWX0Hs4jQIDATgLeAOzULXslQIAAAQI3CQgAN0FahgABAgQI7CQgAOzU
LXslQIAAAQI3CQgAN0FahgABAgQI7CRgCHCnbm201ysDdtHA3ozSj+5zZe8z9mlNAqsEPPvnpY9+j5xf
af0V3gCsN3dHAgQIECDwuIAA8HgLbIAAAQIECKwXEADWm7sjAQIECBB4XEAAeLwFNkCAAAECBNYLGAJc
b+6ObwSOBpFWDdtE9zna05tSfEyAAIG0At4ApG2NjREgQIAAgXkCAsA8WysTIECAAIG0AgJA2tbYGAEC
BAgQmCcgAMyztTIBAgQIEEgrYAjww9ZEg2LRUobHIpXPjkWWo3347I6uIpBDwHOeow/VduENQLWOqocA
AQIECAwICAADSE4hQIAAAQLVBASAah1VDwECBAgQGBAQAAaQnEKAAAECBKoJGAJ809GrwzfR9dEw25tt
+PhAILKMzA8ud5gAAQJtBbwBaNt6hRMgQIBAZwEBoHP31U6AAAECbQUEgLatVzgBAgQIdBYQADp3X+0E
CBAg0FZAAGjbeoUTIECAQGcBfwXQuftqHxaI/rIg+guE4QWdSOBhAc/vww1IcHtvABI0wRYIECBAgMBq
AQFgtbj7ESBAgACBBAICQIIm2AIBAgQIEFgtIACsFnc/AgQIECCQQEAASNAEWyBAgAABAqsFBIDV4u5H
gAABAgQSCAgACZpgCwQIECBAYLWAALBa3P0IECBAgEACAQEgQRNsgQABAgQIrBbwTYCrxd1vukD0DWfR
N/ld3cjomtF+rt7b9QQIrBcY/Zlfv7PP7ugNwGduriJAgAABAlsLCABbt8/mCRAgQIDAZwICwGduriJA
gAABAlsLCABbt8/mCRAgQIDAZwKGAD9zcxWBYYFocMhg4DCfEwk8IhD93D6ykYk39QZgIq6lCRAgQIBA
VgEBIGtn7IsAAQIECEwUEAAm4lqaAAECBAhkFRAAsnbGvggQIECAwEQBQ4ATcS2dR+DM0N2K4Z+je5zZ
Zx7ddTs5clu3A3cikF9g9PeINwD5e2mHBAgQIEDgdgEB4HZSCxIgQIAAgfwCAkD+HtkhAQIECBC4XUAA
uJ3UggQIECBAIL+AAJC/R3ZIgAABAgRuF/BXALeTWpDA5wLRlPvoRO/nd113ZVTfuru7E4Fxgejn7snn
N9rPeDXxmd4AxC6OEiBAgACB0gICQOn2Ko4AAQIECMQCAkDs4igBAgQIECgtIACUbq/iCBAgQIBALGAI
MHZxtLFANGzz5PDP6L2jfZ9p4+h9zqzpXAKVBK7+jGWz8AYgW0fshwABAgQILBAQABYguwUBAgQIEMgm
IABk64j9ECBAgACBBQICwAJktyBAgAABAtkEDAFm64j9pBQYHf55cpDuyXunbJpNESDwUsAbgJc8PiRA
gAABAjUFBICafVUVAQIECBB4KSAAvOTxIQECBAgQqCkgANTsq6oIECBAgMBLAUOAL3l8SOCcQDQsaDjv
nOEdZ0d9uGPdFWt4XlYou8dfAt4AeA4IECBAgEBDAQGgYdOVTIAAAQIEBADPAAECBAgQaCggADRsupIJ
ECBAgIAhQM8AgckC0UCaQa/36JHb+6v2P2O07jPP0Oia++up4IyANwBntJxLgAABAgSKCAgARRqpDAIE
CBAgcEZAADij5VwCBAgQIFBEQAAo0khlECBAgACBMwKGAM9oOZfATQJHQ1lnBrtu2srpZY72fnohF1wS
0IdLfC7+U8AbAI8BAQIECBBoKCAANGy6kgkQIECAgADgGSBAgAABAg0FBICGTVcyAQIECBAQADwDBAgQ
IECgoYC/AmjYdCXnFTDZnbc3dkagmoA3ANU6qh4CBAgQIDAgIAAMIDmFAAECBAhUExAAqnVUPQQIECBA
YEBAABhAcgoBAgQIEKgmYAjwgY5GX/dq+OuBRrglAQIEGgt4A9C4+UonQIAAgb4CAkDf3qucAAECBBoL
CACNm690AgQIEOgrIAD07b3KCRAgQKCxgADQuPlKJ0CAAIG+AgJA396rnAABAgQaCwgAjZuvdAIECBDo
KyAA9O29ygkQIECgsYAA0Lj5SidAgACBvgK+CfBN74++oS/6Nr83S738OFrv6N4vF/IhAQIECBAYEPAG
YADJKQQIECBAoJqAAFCto+ohQIAAAQIDAgLAAJJTCBAgQIBANQEBoFpH1UOAAAECBAYEDAEOID11SjQY
eLQXA4NHMo4TIECAQCTgDUCk4hgBAgQIECguIAAUb7DyCBAgQIBAJCAARCqOESBAgACB4gICQPEGK48A
AQIECEQChgAjlYFj0dDdmaG9gVucOiW6d7THU4s6mQABAgTKCngDULa1CiNAgAABAscCAsCxjU8IECBA
gEBZAQGgbGsVRoAAAQIEjgUEgGMbnxAgQIAAgbICAkDZ1iqMAAECBAgcC/grgGOb059EU/fRdP7phV1A
gAABAgRuFvAG4GZQyxEgQIAAgR0EBIAdumSPBAgQIEDgZgEB4GZQyxEgQIAAgR0EBIAdumSPBAgQIEDg
ZgFDgDeD/nu5aDDw3+f89d8zhgWjNUf3E+3RMQIE7hWIfkajO/i5jVQcuyrgDcBVQdcTIECAAIENBQSA
DZtmywQIECBA4KqAAHBV0PUECBAgQGBDAQFgw6bZMgECBAgQuCrQYggwGrQxVHP10XE9AQJnBKLfQ6PX
R9f6HTaq57wjAW8AjmQcJ0CAAAEChQUEgMLNVRoBAgQIEDgSEACOZBwnQIAAAQKFBQSAws1VGgECBAgQ
OBJoMQR4VHym42cGeqKBoKiWM2tG1ztGgAABAnUFvAGo21uVESBAgACBQwEB4JDGBwQIECBAoK6AAFC3
tyojQIAAAQKHAgLAIY0PCBAgQIBAXYEffw6K/ZG9vNGht6t1GJq7KnjP9Wf6rWf3mFvlGYHRZ91z/kx/
qt/VG4DqHVYfAQIECBAIBASAAMUhAgQIECBQXUAAqN5h9REgQIAAgUBAAAhQHCJAgAABAtUFDAF+2GFD
OR/C/euy0SGof1328j/15iWPDwkQIPC3gDcAHgQCBAgQINBQQABo2HQlEyBAgAABAcAzQIAAAQIEGgoI
AA2brmQCBAgQICAAeAYIECBAgEBDgf/uUPPRVPeMCfJRj+jeR/scXdN5BAgQIEBglYA3AKuk3YcAAQIE
CCQSEAASNcNWCBAgQIDAKgEBYJW0+xAgQIAAgUQCAkCiZtgKAQIECBBYJbDFEOARRjR0Fw3nHV3v+PMC
V3sYXf98VXZAgACB/ALeAOTvkR0SIECAAIHbBQSA20ktSIAAAQIE8gsIAPl7ZIcECBAgQOB2AQHgdlIL
EiBAgACB/AJbDwFGvNFQmMHASCrvsaiHeXdrZwQIENhTwBuAPftm1wQIECBA4JKAAHCJz8UECBAgQGBP
AQFgz77ZNQECBAgQuCQgAFziczEBAgQIENhT4MefA1d/7Ln1a7teNRhooO1anypcfeZZ87xU6LgaCOwh
4A3AHn2ySwIECBAgcKuAAHArp8UIECBAgMAeAgLAHn2ySwIECBAgcKuAAHArp8UIECBAgMAeAuW+CTAb
++gAmOGvbJ37bD+j/T5aPbres3Gk5TgBAlcEvAG4oudaAgQIECCwqYAAsGnjbJsAAQIECFwREACu6LmW
AAECBAhsKiAAbNo42yZAgAABAlcE2g4BRoNV0QDWFdwz10b3jvZ4Zk3nEiBAgACBIwFvAI5kHCdAgAAB
AoUFBIDCzVUaAQIECBA4EhAAjmQcJ0CAAAEChQUEgMLNVRoBAgQIEDgSEACOZBwnQIAAAQKFBdr+FUDU
02jqPprOj66dcezo3tE+Z9zfmgQIECBQV8AbgLq9VRkBAgQIEDgUEAAOaXxAgAABAgTqCggAdXurMgIE
CBAgcCggABzS+IAAAQIECNQVMAT4prdnBu6Ohvbe3OL0x9F9zuzz9A1dEApEfQhPdJAAAQIJBbwBSNgU
WyJAgAABArMFBIDZwtYnQIAAAQIJBQSAhE2xJQIECBAgMFtAAJgtbH0CBAgQIJBQwBDgjU2JBvFWDYpF
94n2c2O5rZaKfFsBKJYAgXIC3gCUa6mCCBAgQIDAewEB4L2RMwgQIECAQDkBAaBcSxVEgAABAgTeCwgA
742cQYAAAQIEygkYApzc0mgQz0DZZPSLyz/Zn+h5uViOywkQIBAKeAMQsjhIgAABAgRqCwgAtfurOgIE
CBAgEAoIACGLgwQIECBAoLaAAFC7v6ojQIAAAQKhgCHAkGW/g4bH9uqZfu3VL7slUFHAG4CKXVUTAQIE
CBB4IyAAvAHyMQECBAgQqCggAFTsqpoIECBAgMAbAQHgDZCPCRAgQIBARQEBoGJX1USAAAECBN4I+CuA
N0A+JnBVwMT/VUHXEyAwQ8AbgBmq1iRAgAABAskFBIDkDbI9AgQIECAwQ0AAmKFqTQIECBAgkFxAAEje
INsjQIAAAQIzBAwBzlC15hYCX19fW+zTJgkQIDBDwBuAGarWJECAAAECyQUEgOQNsj0CBAgQIDBDQACY
oWpNAgQIECCQXEAASN4g2yNAgAABAjMEBIAZqtYkQIAAAQLJBQSA5A2yPQIECBAgMENAAJihak0CBAgQ
IJBcQABI3iDbI0CAAAECMwQEgBmq1iRAgAABAskFfBNg8gbZ3l4C/q9/9+qX3RLoLOANQOfuq50AAQIE
2goIAG1br3ACBAgQ6CwgAHTuvtoJECBAoK2AANC29QonQIAAgc4CAkDn7qudAAECBNoKCABtW69wAgQI
EOgsIAB07r7aCRAgQKCtgADQtvUKJ0CAAIHOAgJA5+6rnQABAgTaCvgmwLat71X419dXr4JVS4AAgTcC
3gC8AfIxAQIECBCoKCAAVOyqmggQIECAwBsBAeANkI8JECBAgEBFAQGgYlfVRIAAAQIE3ggIAG+AfEyA
AAECBCoKCAAVu6omAgQIECDwRkAAeAPkYwIECBAgUFFAAKjYVTURIECAAIE3AgLAGyAfEyBAgACBigIC
QMWuqokAAQIECLwR8FXAb4B8TOBI4OfPn0cfOU6AAIH0At4ApG+RDRIgQIAAgfsFBID7Ta1IgAABAgTS
CwgA6VtkgwQIECBA4H4BAeB+UysSIECAAIH0AgJA+hbZIAECBAgQuF9AALjf1IoECBAgQCC9gACQvkU2
SIAAAQIE7hcQAO43tSIBAgQIEEgvIACkb5ENEiBAgACB+wV8E+D9po+s+PX19dt9fVPdbyQOECBAgMD/
C3gD4FEgQIAAAQINBQSAhk1XMgECBAgQEAA8AwQIECBAoKGAANCw6UomQIAAAQICgGeAAAECBAg0FBAA
GjZdyQQIECBAQADwDBAgQIAAgYYCAkDDpiuZAAECBAgIAJ4BAgQIECDQUMA3AT7Q9Ogb+qJv8ntga25J
gAABAk0EvAFo0mhlEiBAgACBXwUEgF81/JsAAQIECDQREACaNFqZBAgQIEDgVwEB4FcN/yZAgAABAk0E
BIAmjVYmAQIECBD4VUAA+FXDvwkQIECAQBMBAaBJo5VJgAABAgR+FRAAftXwbwIECBAg0ERAAGjSaGUS
IECAAIFfBQSAXzX8mwABAgQINBHwVcCFGx19vXD0NcSFCZRGgAABAgcC3gAcwDhMgAABAgQqCwgAlbur
NgIECBAgcCAgABzAOEyAAAECBCoLCACVu6s2AgQIECBwICAAHMA4TIAAAQIEKgsIAJW7qzYCBAgQIHAg
IAAcwDhMgAABAgQqCwgAlburNgIECBAgcCAgABzAOEyAAAECBCoL+CbAJN2NvqEv+ia/JNu1jUkCoz2P
npdJW7IsAQJFBbwBKNpYZREgQIAAgVcCAsArHZ8RIECAAIGiAgJA0cYqiwABAgQIvBIQAF7p+IwAAQIE
CBQVMARYtLHKyi0wOux3VMXV66N1DRZGKuePnekN8/O+rrhPwBuA+yytRIAAAQIEthEQALZplY0SIECA
AIH7BASA+yytRIAAAQIEthEQALZplY0SIECAAIH7BAwB3me5xUrRgJJBpLmti8zn3vGz1aN9eja+LSOf
708/+1e0JvPPLF11XsAbgPNmriBAgAABAtsLCADbt1ABBAgQIEDgvIAAcN7MFQQIECBAYHsBAWD7FiqA
AAECBAicFxAAzpu5ggABAgQIbC/grwC2b+H1AkwiXze0wr4C0fO/bzV2TmBcwBuAcStnEiBAgACBMgIC
QJlWKoQAAQIECIwLCADjVs4kQIAAAQJlBASAMq1UCAECBAgQGBcwBDhutfzMo68ENbS0vBUtbnj0vGUv
3s9D9g7ZX1YBbwCydsa+CBAgQIDARAEBYCKupQkQIECAQFYBASBrZ+yLAAECBAhMFBAAJuJamgABAgQI
ZBUwBJi1My/2FQ1r3T0IdbRedO8XW/VRQoGde3j0XCZk/m1LO7v/VowDJQS8ASjRRkUQIECAAIFzAgLA
OS9nEyBAgACBEgICQIk2KoIAAQIECJwTEADOeTmbAAECBAiUEDAEWKKN64qIhrAMN63zd6f8An4e8vfI
Dv9PwBsATwIBAgQIEGgoIAA0bLqSCRAgQICAAOAZIECAAAECDQUEgIZNVzIBAgQIEDAEWOQZiAaPooG9
IuUqo5hAtmc1+nkqRq4cAv/xBsBDQIAAAQIEGgoIAA2brmQCBAgQICAAeAYIECBAgEBDAQGgYdOVTIAA
AQIEDAEWfgaiQaZsw1aF+ZUWCGR8/qKfk2DrDhEoJ+ANQLmWKogAAQIECLwXEADeGzmDAAECBAiUExAA
yrVUQQQIECBA4L2AAPDeyBkECBAgQKCcgABQrqUKIkCAAAEC7wX8FcB7I2e8EYgmuztMVo/WHVlE1x4x
//HHH7999OPHj9+ORQeie0fnXT12pp6r9/r0+lUWn+7PdQRWC3gDsFrc/QgQIECAQAIBASBBE2yBAAEC
BAisFhAAVou7HwECBAgQSCAgACRogi0QIECAAIHVAj/+HIz5fcJo9S7cb5nAk8NaTw5hPVn3suY2vdGT
z1VTcmUXEfAGoEgjlUGAAAECBM4ICABntJxLgAABAgSKCAgARRqpDAIECBAgcEZAADij5VwCBAgQIFBE
wDcBFmnkaBnRwNSqAbnoPtF+RmtxXj8Bz0u/nqt4noA3APNsrUyAAAECBNIKCABpW2NjBAgQIEBgnoAA
MM/WygQIECBAIK2AAJC2NTZGgAABAgTmCRgCnGe7zcrRYFU0sLdNQcFGO9QYlL3Noag/22zeRglsKuAN
wKaNs20CBAgQIHBFQAC4oudaAgQIECCwqYAAsGnjbJsAAQIECFwREACu6LmWAAECBAhsKuD/DnjTxj21
7RXDgRkHwlbU/VRPV943Y29X1u9eBDIJeAOQqRv2QoAAAQIEFgkIAIug3YYAAQIECGQSEAAydcNeCBAg
QIDAIgEBYBG02xAgQIAAgUwCvgkwUzfs5W+Bo4G7JwfInry3x4IAAQIzBLwBmKFqTQIECBAgkFxAAEje
INsjQIAAAQIzBASAGarWJECAAAECyQUEgOQNsj0CBAgQIDBDQACYoWpNAgQIECCQXMBfASRvULbtRdPw
R1P72fZuPwQIECDwLeANwLeFfxEgQIAAgTYCAkCbViuUAAECBAh8CwgA3xb+RYAAAQIE2ggIAG1arVAC
BAgQIPAtYAjw28K/PhQwGPghnMsIECDwoIA3AA/iuzUBAgQIEHhKQAB4St59CRAgQIDAgwICwIP4bk2A
AAECBJ4SEACekndfAgQIECDwoMD/AtON9jTfFOXiAAAAAElFTkSuQmCC
`

const bigImageAscii = `""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""l++JJJJ
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""!)))n#$$$$$$
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""">C%$$$$$$#\lll
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""-a$$h/]]]];""""
"""""I/Xv~~;""""""""""""""""""""""""""""""""""""""""""""""""""""_b$$*]""""""""""
"""""|$$$$$adQ|||""""""""""""""""""""""""""""""""""""""""""""""fo$$M_"""""""xddf
"""""|$$8O888$$$$*n?ll""""""""""""""""""""""""""""""""""""""";f$$$Ol"""""""b$$$$
"""""|$$*"""")vW$$$$$BmuI"""""""""""""""""""""""""""""""""")r#$$Wv!""""""""o$$$$
"""""|$$*""""""Il~nn*8$$888q?""""""""""""""""""""""""""""Ih$$B8fI""""""""]h$$$$$
"""""|$$*"""""""""""";)zmp$$$Q}""""""""""""""""""""""""""O$$W1""""""""""iC$$$$$$
"""""|$$*""Irt;"""""""""",?w@$$z""""""""""""""""""""""""?o$$O"""""""""""|$$$$$$$
"""""|$$*""w$$v"""""""""""""w$$o?"""""""""""""""""""""""r$$W}"""""""""""|$$$$$$$
"""""|$$*""w$$v""""""""""""">88$Wk|I"""""""""",lllllllllu$$o"""""""""""xW$$$$$B8
"""""|$$*""w$$v"""""""""""""""<#$$$#f]"">]]]vLO$$$$$$$$$$$$o"""""""""""tbbbbOt+"
"""""|$$*""w$$v""""""""""""""""l~X%$$$**8$$$$$88wXXXXXXC8@$b""""""""""""""""""""
"""""|$$*""w$$v""""""""""""""""""">coooooo||||I""""""""""]|"""""""""""""""""""""
"""""|$$*""w$$M}""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""|$$*"""0$$$OY<"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""|$$*""""|L#$$p<"""""""""""""""""""""""""""""""""""t]"""""""""""""""""""""""
"""""}W$$p>""""}tbC<""""";]>""""""""""""""""""""""""""0$W}""""""""""""""""""""""
""""""tM$$&oj""""""""""""#$&[""""""""""""""""""""""""""+i"""""""""""""""""""""""
"""""""InW$$$>"""""""""""~n{:"""":~i""""""""""""""""""""""""""""""""""""""""""""
"""""""""?h$$8bzI""""""""""""""""m$8|"""""""""""""""""""""""""""""""""""""""""""
"""""""""";\nM$$8u!""""""""""""lj8$$r"""""""""""""""""""""""""""""""""""""""""""
"""""""""""""lL$$8\"""""""""""<#$$#vi"""""""""""""""""""""""""""""""""""""""""""
""""""""""""""v$$o"""""""""""!J$$#I"""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""v$$o"""""""""""+$$$/""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""v$$o"""""""""""8$$%<""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""v$$M_""""""""""$$$|"""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""]a$$U""""""""""$$$|"""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""O$$*]"""""""""$$$|"""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""iM$$t,""""""""$$$|,?J*znn{:""""""""":l\nl""""""""""""""""""""""""
""""""""""""""""O$$$Z""""""""$$$|~$$$$$$M]"""""l]]Yq$$$o""""""""""""""""""""""""
"""""""""""""""""1B$$k)""""""$$$|~$$$$$Jl""""I_W$$$880?<""""""""""""""""""""""""
""""""""""""""""""<b$$pi"""""$$$v~*$#B8t"";]XW$$$ht"""""""""""""""""""""""""""""
"""""""""""""""""""t8$$&v""""$$$$*M$W@Booo#$$$%x+:""""""""""""""""""""""""""""""
"""""""""""""""""""""u$$$Y+""ltYbbbbbbbbbbbbz<""""""""""""""""""""""""""""""""""
""""""""""""""""""""";/o$$w"""""""""""""""""""""""""""""""""""""""""""""""""""""
`
